# Generated by Django 4.0.2 on 2022-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('contact_number', models.BigIntegerField()),
                ('student_class', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('fees', models.BigIntegerField()),
                ('certificate', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'add_student',
            },
        ),
        migrations.CreateModel(
            name='AddTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('teacher_class', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('contact_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('certificate', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'add_teacher',
            },
        ),
    ]
