# Generated by Django 4.0.2 on 2022-04-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddTeacher',
            new_name='AddTeachers',
        ),
    ]
