# Generated by Django 4.0.2 on 2022-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
